service: product-browser-api

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}
    JWT_SECRET: ${env:JWT_SECRET}
    PROFILE_PICS_BUCKET: ${env:PROFILE_PICS_BUCKET}
    PRODUCT_IMAGES_BUCKET: ${env:PRODUCT_IMAGES_BUCKET}

functions:
  register:
    handler: src/handlers/auth/register.handler
    events:
      - http:
          path: register
          method: post
          cors: true
  # Define other functions similarly...

resources:
  Resources:
    ProfilePicsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:PROFILE_PICS_BUCKET}
        AccessControl: Private
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ['*']
              AllowedMethods: [GET, PUT, POST, DELETE]
              AllowedOrigins: ['*']
              MaxAge: 3000